"""Best-effort Sigma -> Wazuh local rule XML translator.

No official pySigma-Wazuh backend exists (verified: pysigma-backend-wazuh is
not a published package), so unlike the Splunk/Elasticsearch exporters this
is a hand-built translator, not a call into a maintained pySigma backend.
It only translates the rule's main (non-`filter_*`) selections into positive
`<field>` matches - Sigma's `and not filter_*` exclusion logic has no direct
Wazuh XML equivalent in this simple mapping and is NOT translated, which is
called out explicitly in the returned warnings every time.
"""
from __future__ import annotations

import re
from xml.sax.saxutils import escape as xml_escape
from xml.sax.saxutils import quoteattr as xml_quoteattr

from detection_forge.attack.attack_data import parse_technique_id
from detection_forge.models import ExportedRule, GeneratedRule

_LEVEL_MAP = {
    "informational": 3,
    "low": 5,
    "medium": 7,
    "high": 10,
    "critical": 13,
}

_FIELD_MAP = {
    "Image": "win.eventdata.Image",
    "CommandLine": "win.eventdata.CommandLine",
    "ParentImage": "win.eventdata.ParentImage",
    "ParentCommandLine": "win.eventdata.ParentCommandLine",
    "TargetFilename": "win.eventdata.TargetFilename",
    "TargetImage": "win.eventdata.TargetImage",
    "SourceImage": "win.eventdata.SourceImage",
    "User": "win.eventdata.User",
    "GrantedAccess": "win.eventdata.GrantedAccess",
    "DestinationIp": "win.eventdata.DestinationIp",
    "DestinationHostname": "win.eventdata.DestinationHostname",
}

_BASE_RULE_ID = 100100


def _map_field(field: str) -> str:
    return _FIELD_MAP.get(field, f"win.eventdata.{field}")


def _value_to_pcre2(value) -> str:
    from sigma.types import SigmaString

    if isinstance(value, SigmaString):
        return value.to_regex().regexp.to_plain()
    return re.escape(str(value))


def _main_selection_items(parsed) -> tuple[list, list[str]]:
    """Returns (detection_items_from_non_filter_selections, skipped_filter_names)."""
    from sigma.rule import SigmaDetection

    items = []
    skipped = []
    for name, detection in parsed.detection.detections.items():
        if name.lower().startswith("filter"):
            skipped.append(name)
            continue
        for sub in detection.detection_items:
            if isinstance(sub, SigmaDetection):
                continue  # nested groups not flattened in this best-effort translator
            if sub.field:
                items.append(sub)
    return items, skipped


def export_wazuh(rule: GeneratedRule) -> ExportedRule:
    filename = f"{rule.sigma_id}.wazuh.xml"
    warnings = [
        "No official Sigma-to-Wazuh converter exists; field mappings and the "
        "<if_sid> base rule are best-effort and MUST be reviewed/adjusted for "
        "your Wazuh decoder before deployment."
    ]

    try:
        import yaml as pyyaml
        from sigma.rule import SigmaRule

        parsed = SigmaRule.from_yaml(rule.rule_yaml)
        raw = pyyaml.safe_load(rule.rule_yaml) or {}

        items, skipped_filters = _main_selection_items(parsed)
        if skipped_filters:
            warnings.append(
                "Sigma exclusion selection(s) "
                + ", ".join(skipped_filters)
                + " use 'and not' logic that has no direct Wazuh XML equivalent here and "
                "were NOT translated - add manual exclusions in Wazuh if needed."
            )

        level_name = str(raw.get("level", "medium")).lower()
        wazuh_level = _LEVEL_MAP.get(level_name, 7)

        field_lines = []
        for item in items:
            mapped = _map_field(item.field)
            values = item.value if isinstance(item.value, list) else [item.value]
            patterns = [_value_to_pcre2(v) for v in values]
            pattern = "|".join(f"(?:{p})" for p in patterns) if len(patterns) > 1 else (patterns[0] if patterns else "")
            if not pattern:
                continue
            # quoteattr (not escape) is required here: it also escapes `"`, which plain
            # xml_escape does not - mapped/pattern ultimately trace back to LLM-drafted
            # field names, and an unescaped `"` would break out of this XML attribute.
            field_lines.append(f'    <field name={xml_quoteattr(mapped)} type="pcre2">{xml_escape(pattern)}</field>')

        tags = raw.get("tags", []) or []
        mitre_lines = []
        for tag in tags:
            technique_id = parse_technique_id(str(tag))
            if technique_id:
                mitre_lines.append(f"      <id>{xml_escape(technique_id)}</id>")

        title = xml_escape(str(raw.get("title", rule.title or "Untitled rule")))
        description_extra = xml_escape(str(raw.get("description", "")))[:400]

        mitre_block = ""
        if mitre_lines:
            mitre_block = "\n    <mitre>\n" + "\n".join(mitre_lines) + "\n    </mitre>"

        xml_content = (
            "<!-- Generated by Detection Forge - REVIEW BEFORE DEPLOYING.\n"
            "     Base rule id, decoder assumptions, and field mappings are best-effort. -->\n"
            '<group name="detection_forge,">\n'
            f'  <rule id="{_BASE_RULE_ID}" level="{wazuh_level}">\n'
            "    <!-- TODO: set a real <if_sid> pointing at the base decoder rule for your\n"
            "         log source (e.g. Sysmon/Windows event channel) so this rule only\n"
            "         evaluates against relevant events. -->\n"
            "    <if_sid>REPLACE_ME_BASE_SID</if_sid>\n"
            f"{chr(10).join(field_lines)}\n"
            f"    <description>{title}{(' - ' + description_extra) if description_extra else ''}</description>{mitre_block}\n"
            "  </rule>\n"
            "</group>\n"
        )

        if not field_lines:
            warnings.append("No field conditions could be translated - this export is a skeleton only.")
    except Exception as exc:
        return ExportedRule(
            target="wazuh",
            content=f"<!-- Wazuh conversion failed: {exc} -->",
            filename=filename,
            warnings=[f"Wazuh conversion failed: {exc}"],
        )

    return ExportedRule(target="wazuh", content=xml_content, filename=filename, warnings=warnings)
