"""Client-facing summary: the thing an MSP attaches to a QBR or a weekly email
to show the client what their security spend is actually catching - part of
the packaging story, not just an internal artifact."""
from __future__ import annotations

from soc_copilot.models import PipelineResult

_PRIORITY_ORDER = ("P1", "P2", "P3", "P4")


def render_client_digest(result: PipelineResult, period_label: str = "This period") -> str:
    client = result.client
    lines: list[str] = []
    lines.append(f"# Security Summary — {client.name} ({period_label})")
    lines.append("")
    lines.append(f"**Alerts ingested:** {result.total_alerts_ingested}  |  **Correlated incidents:** {len(result.incidents)}  |  **Flagged for review:** {result.needs_review_count}")
    lines.append("")

    by_priority: dict[str, int] = {p: 0 for p in _PRIORITY_ORDER}
    for r in result.incidents:
        by_priority[r.triage.suggested_priority.value] = by_priority.get(r.triage.suggested_priority.value, 0) + 1
    lines.append("**By priority:** " + ", ".join(f"{p}: {by_priority.get(p, 0)}" for p in _PRIORITY_ORDER))
    lines.append("")

    lines.append("| Priority | Severity | Host/User | Verdict | Summary |")
    lines.append("|---|---|---|---|---|")
    ordered = sorted(result.incidents, key=lambda r: (_PRIORITY_ORDER.index(r.triage.suggested_priority.value), r.incident.opened_at))
    for r in ordered:
        target = r.incident.host or r.incident.user or "(unknown)"
        lines.append(
            f"| {r.triage.suggested_priority.value} | {r.triage.severity.value} | {target} | "
            f"{r.triage.verdict.value} | {r.triage.summary} |"
        )
    lines.append("")
    lines.append(f"_Estimated AI triage cost this period: ${result.total_cost_usd:.4f}_")
    lines.append("")
    lines.append("_Generated by SOC Copilot._")
    return "\n".join(lines)
