"""Render one incident as a PSA-ready ticket note (ConnectWise/Autotask/Halo/etc.
all accept plain Markdown-ish text in a ticket description field)."""
from __future__ import annotations

from soc_copilot.config import settings
from soc_copilot.models import Client, Incident, Recommendation, TriageResult, UsageCost

_PHASE_ORDER = ("contain", "eradicate", "recover", "communicate")
_PHASE_LABEL = {"contain": "Contain", "eradicate": "Eradicate", "recover": "Recover", "communicate": "Communicate"}


def render_ticket_note(
    incident: Incident,
    triage: TriageResult,
    recommendation: Recommendation,
    client: Client,
    usage: UsageCost | None = None,
) -> str:
    lines: list[str] = []
    lines.append(f"# [{triage.suggested_priority.value}] {triage.severity.value.upper()} - {incident.host or incident.user} ({recommendation.playbook_name})")
    lines.append("")
    lines.append(f"**Client:** {client.name} ({client.client_id}, tier: {client.criticality_tier})")
    lines.append(f"**Window:** {incident.opened_at.isoformat()} to {incident.closed_at.isoformat()}")
    lines.append(f"**Host / User:** {incident.host or '(none)'} / {incident.user or '(none)'}")
    lines.append(f"**Sources:** {', '.join(incident.sources)}")
    origin = "LLM-drafted" if triage.is_llm_generated else "heuristic fallback (no ANTHROPIC_API_KEY)"
    lines.append(f"**Verdict:** {triage.verdict.value} — confidence {triage.confidence}% ({origin}, model: {triage.model_used})")
    lines.append("")
    lines.append(f"**Summary:** {triage.summary}")
    lines.append("")
    lines.append("**Analyst notes:**")
    lines.append(triage.analyst_notes)
    lines.append("")

    if triage.attack_techniques:
        tag_bits = []
        for t in triage.attack_techniques:
            label = f"{t.technique_id} ({t.technique_name})" if t.technique_name else f"{t.technique_id} (unrecognized - verify manually)"
            tag_bits.append(label)
        lines.append(f"**MITRE ATT&CK:** {', '.join(tag_bits)}")
        lines.append("")

    lines.append(f"**Correlated alerts ({len(incident.alerts)}):**")
    for a in incident.alerts:
        lines.append(f"- [{a.source}] {a.timestamp.isoformat()} `{a.alert_id}` — {a.title} (severity: {a.severity_raw or a.severity.value})")
    lines.append("")

    lines.append("**Recommended actions:**")
    for phase in _PHASE_ORDER:
        steps = recommendation.steps.get(phase, [])
        if not steps:
            continue
        lines.append(f"*{_PHASE_LABEL[phase]}:*")
        for step in steps:
            lines.append(f"- {step}")
    lines.append("")
    if recommendation.tailored_notes:
        lines.append("**Incident-specific notes:**")
        lines.append(recommendation.tailored_notes)
        lines.append("")

    if usage and (usage.input_tokens or usage.output_tokens):
        cost = usage.cost_usd(settings.cost_per_1m_input, settings.cost_per_1m_output)
        lines.append(f"_Triage cost: ~${cost:.4f} ({usage.input_tokens} in / {usage.output_tokens} out tokens)_")

    lines.append("")
    lines.append("_Generated by SOC Copilot. AI-assisted triage — review before closing this ticket._")
    return "\n".join(lines)
